train:
  number_of_problems_per_batch: 16
  num_samples_per_problem: 8
  save_policy_to_disk_every_n: 10

  learning_rate: 2e-5
  epochs: 1
  beta: 0.005
  mu: 2

teacher_model:
  model_name_or_path: Qwen/Qwen3.5-9B
  use_qwen3_5: true
  lora:
      enable: True
      rank: 64
      alpha: 128
      target_modules:
        - q_proj
        - k_proj
        - v_proj
        - o_proj
        - gate_proj
        - up_proj
        - down_proj
        - out_proj
        - in_proj_qkv
        - in_proj_z
        # - in_proj_b
        # - in_proj_a
      dropout: 0.05
      bias: "none"
  vllm:
    temperature: 1.0
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 8
    max_number_of_instances: -1
    load_and_unload: true
    use_v0: true
    enforce_eager: true

student_model:
  model_name_or_path: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 8
    max_number_of_instances: -1
    use_v0: false

    load_and_unload: true

judge_model:
  model_name_or_path: Qwen/Qwen3-14B-AWQ
  vllm:
    temperature: 0.6
    max_length: 12000
    max_num_seqs: 512
    gpu_memory_utilization: 0.4
    number_of_gpus_per_instance: 8
    max_number_of_instances: -1
    load_and_unload: false
    use_v0: false


reward_model:
  model_name_or_path: Answer # If we set this to None we get the -r_sol run.

logging:
  log: true
  log_project: train-rl
  log_run_name: ai-turor-test
  run_group: 9b
  log_tags: ["9b"]
  save_dir: checkpoints/9b
  save_steps: 10


generation:

  # This turns on thinking.
  use_thinking: true
  # force_thinking: true

  # This turns on the hard lambda.
  extra_penalty_for_rejected_judges: 1.0 # This is the actual lambda we use.
  ignore_rejected_judge: false # If we set this to false we get the soft lambda runs.

  use_experimental_shared_memory: false
  forced_conversation_type: attempt # 'guided' or 'attempt'
  max_turns: 15
  
  # If we turn this on we get the lambda=0.0 run
  # number_judge_attempts: 0
  # judges_rules_prompts_paths: {}

dataset:
  train_datasets:
    - name_or_path: data/datasets/train.jsonl
      split: train
      is_json: true